package com.desktop.lumi.home.presentation

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.desktop.lumi.analytics.Analytics
import com.desktop.lumi.db.com.desktop.lumi.NotificationScheduler
import com.desktop.lumi.domain.model.Reflection
import com.desktop.lumi.domain.repository.ReflectionRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

class ReflectionViewModel(
    private val reflectionRepository: ReflectionRepository,
    private val analytics: Analytics? = null,
    private val scheduler: NotificationScheduler?
) : ViewModel() {

    private val _uiState = MutableStateFlow(ReflectionUiState())
    val uiState: StateFlow<ReflectionUiState> = _uiState

    data class ReflectionUiState(
        val mood: Int = 3,
        val note: String = ""
    )

    fun onMoodSelected(mood: Int) {
        _uiState.value = _uiState.value.copy(mood = mood)
    }

    fun onNoteChange(note: String) {
        _uiState.value = _uiState.value.copy(note = note)
    }

    @OptIn(ExperimentalTime::class)
    fun saveReflection() {
        viewModelScope.launch {
            val state = _uiState.value

            val reflection = Reflection(
                id = 0L,                           // auto-generated by SQLDelight
                mood = state.mood,
                note = state.note,
                timestamp = Clock.System.now().toEpochMilliseconds()
            )

            reflectionRepository.saveReflection(reflection)
            scheduler?.scheduleStreakNudge()

            // Track analytics event
            analytics?.logEvent(
                "reflection_logged",
                mapOf(
                    "mood" to state.mood,
                    "has_note" to state.note.isNotEmpty(),
                    "note_length" to state.note.length
                )
            )

            _uiState.value = ReflectionUiState()
        }
    }
}
